test-clang-compilation:
  extends:
    - .gitlab-shared-clang
  script:
    - export CFLAGS="-Wall -Werror"
    - ./configure
    - make -j

test-clang-Wall-script:
  extends:
    - .gitlab-shared-clang
  script:
    - export CFLAGS="-g -O0"
    - export CC=".gitlab/ci/clang-Wall"
    - ./configure
    - make -j CFLAGS="-g -O0 -Werror"

test-scan-build:
  extends:
    - .gitlab-shared-clang
  script:
    - scan-build${COMPILER_VERSION:+-$COMPILER_VERSION} -V ./configure CFLAGS="-g -O0"
    - make clean
    - scan-build${COMPILER_VERSION:+-$COMPILER_VERSION} --status-bugs -maxloop 10 make -j
