test-gcc-compilation:
  extends:
    - .gitlab-shared-gcc
  script:
    - export CFLAGS="-Wall -Werror"
    - ./configure --enable-pwquality --enable-libargon2
    - make -j

test-gcc-Wall-script:
  extends:
    - .gitlab-shared-gcc
  script:
    - export CFLAGS="-g -O0"
    - export CC=".gitlab/ci/gcc-Wall"
    - ./configure --enable-pwquality --enable-libargon2
    - make -j CFLAGS="-g -O0 -Werror"

test-gcc-fanalyzer:
  extends:
    - .gitlab-shared-gcc
  script:
    - export CFLAGS="-Wall -Werror -g -O0 -fanalyzer -fdiagnostics-path-format=separate-events"
    - ./configure --enable-pwquality --enable-libargon2
    - make -j
